set(VGUI2EXTENSION_DEPENDENCY_CACHE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/cache" CACHE PATH "Downloaded dependency cache")
set(VC_LTL_Root "${VGUI2EXTENSION_DEPENDENCY_CACHE_DIR}/VC-LTL-5.3.1" CACHE PATH "VC-LTL binary package root")
set(METAHOOK_SOURCE_PATH "$ENV{METAHOOK_SOURCE_PATH}" CACHE PATH "MetaHook source tree; empty fetches the pinned SDK")
set(SDL2_INCLUDE_DIRS "$ENV{SDL2_INCLUDE_DIRS}" CACHE STRING "Directories containing SDL2/SDL_syswm.h (required)")
set(SDL3_INCLUDE_DIRS "$ENV{SDL3_INCLUDE_DIRS}" CACHE STRING "Directories containing SDL3/SDL_events.h (required)")

function(vgui2extension_prepare_dependencies)
    foreach(version 2 3)
        if(version EQUAL 2)
            set(header SDL2/SDL_syswm.h)
        else()
            set(header SDL3/SDL_events.h)
        endif()
        set(found FALSE)
        set(includes)
        foreach(directory IN LISTS SDL${version}_INCLUDE_DIRS)
            get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
            if(NOT IS_DIRECTORY "${directory}")
                message(FATAL_ERROR "SDL${version}_INCLUDE_DIRS directory does not exist: ${directory}")
            endif()
            if(EXISTS "${directory}/${header}")
                set(found TRUE)
            endif()
            list(APPEND includes "${directory}")
        endforeach()
        if(NOT found)
            message(FATAL_ERROR "Set SDL${version}_INCLUDE_DIRS to directories providing ${header}. VGUI2Extension does not fetch or build SDL.")
        endif()
        set(VGUI2EXTENSION_SDL${version}_INCLUDE_DIRS "${includes}" PARENT_SCOPE)
    endforeach()

    if(METAHOOK_SOURCE_PATH)
        get_filename_component(metahook_source "${METAHOOK_SOURCE_PATH}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
    else()
        include(FetchContent)
        FetchContent_Declare(vgui2extension_metahook
            GIT_REPOSITORY https://github.com/MetaHookSv/MetaHook
            # MetaHook is tracked as a branch: always fetch the latest main.
            GIT_TAG origin/main
            GIT_SUBMODULES ""
            GIT_SUBMODULES_RECURSE FALSE
            SOURCE_SUBDIR include
        )
        FetchContent_MakeAvailable(vgui2extension_metahook)
        set(metahook_source "${vgui2extension_metahook_SOURCE_DIR}")
    endif()
    foreach(required include/metahook.h include/HLSDK/common/interface.cpp include/SourceSDK/filesystem.cpp include/vgui_controls/Panel.cpp)
        if(NOT EXISTS "${metahook_source}/${required}")
            message(FATAL_ERROR "METAHOOK_SOURCE_PATH is missing ${required}: ${metahook_source}")
        endif()
    endforeach()
    set(METAHOOK_SOURCE_PATH "${metahook_source}" PARENT_SCOPE)
    message(STATUS "METAHOOK_SOURCE_PATH: ${metahook_source}")
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VCLTL.cmake")
    vgui2extension_prepare_vcltl()
endfunction()
